---
title: Курс "Advanced R"
description: Материалы курса 
---
 

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
```



# **Часть 1.** Создание html документа 

В этой части курса мы учимся создавать простейшие html документы, используя язык разметки документов `rmarkdown`

## Материалы для упражнения
Задание:

1. Создайте новый RMD документ
2. Далее заполните его содержимым статьи, текст которой в формате Word можно скачать ниже. При заполнении используйте ту разбивку на части, которые есть в исходной работе.
3. Создайте рисунок №2 и рисунок №4 прямо из R-кода.
4. Создайте таблицу №3 с помощью генератора таблиц, представленного на сайте (https://www.tablesgenerator.com/markdown_tables)
5. Создайте таблицу №1 и таблицу №2 прямо из R-кода.
6. Остальные рисунки создайте как вставку рисунка из jpg-файла.


- [Текст для упражененя](Advanced_R/Exercises/Khaitov_et_al_Derjugin.docx)

- [файл с данными для рисунка 1](Advanced_R/Exercises/data/myt_all.csv)
- [файл с данными для рисунка 2](Advanced_R/Exercises/data/myt_Z0_all_full.csv)

## Результаты работы над упражнением

- [файл RMD](My_html_project/Khaitov_et_al.Rmd)
- [файл html](My_html_project/Khaitov_et_al.html)

## Домашнее задание по итогам работы 29.01.19

1. Доделайте все до конца.
2. В итоговый RMD файл, сразу перед первым чанком поставьте кусочек кода, который приведен ниже. Это  позволяет менять параметры текста в html документе. 
3. Меняя указанные в этом коде параметры, добейтесь наилучшего вида для финального документа.
4. Полученный html файл пришлите мне до следующего занятия.

*Вот код, который надо вставить*

```
<style type="text/css">

body{ /* Normal  */
      font-size: 18px;
  }
td {  /* Table  */
  font-size: 20px;
}
h1.title {
  font-size: 38px;
  color: DarkRed;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 22px;
  color: DarkBlue;
}
h3 { /* Header 3 */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>

```
## Сданные ДЗ.
Вот Анка и Слава - молодцы! Остальные... Господа, ДЗ надо делать и присылать.

- [Слава RMD](My_html_project/Slava.Rmd)

# **Часть 2.** Работа с библиографией
В этой части курса мы научимся автоматически управлять форматом и стилем списка литературы и ссылками в тексте работы. 

Первый шаг - это научиться создавать файл с тегами, описывающими литературные источники. В последствии мы научимся делать это автоматически из библиографической базы типа Mendeley или Zotero. Однако для начала это надо будет сделать вручную. 

## Домашнее задание по итогам работы 5.02.2019

1. Создайте в блокноте файл my_bibliography.bib (лучше называть его как-то стандартно).
2. По всем статьям, которые цитируются в том файле, с которым мы работаем, надо найти ссылки в поисковике google Академия. 
3. Скопируйте ссылки в формате bibTeX
4. Вставьте эти ссылки в в файл  my_bibliography.bib.
5. Для русскоязычных статей, скорее всего, ничего нормального в google Академия вы не найдете. Поэтому создайте их описание в формате bibTeX ручками по образу и подобию английских ссылок.
6. Готовый файл, включающий все ссылки, пришлите мне до следующего вторника. 

На всякий случай, вот последняя версия RMD файла, который мы сотворили. Можете ее использовать.
- [Слава RMD](My_html_project/Slava.Rmd)

## Создаем список литературы

- [Библиография от Славы](My_html_project/litlist_forcopy.txt)
- [Библиография от Анки](My_html_project/my_bibliography.bib)

# **Часть 3.** Формируем список литературы в html-документе

Вот текущий код, в котором показано, как вставляются бибилографические ссылки, находящиеся в файле .bib, в текст RMD в соответстсвии со стилем, принятым в том или ином журнале

- [RMD файл, со вставленными ссылками](My_html_project/Slava.Rmd)
- [файл .bib с библиографическими данными](My_html_project/my_bibliography.bib)
- [файл .csl c описанием стиля цитирования, используемого в журнале "Animal migration" ](animal-migration.csl)

## Домашнее задание по итогам работы 12.02.2019

1. Доработать файл .bib так, чтобы в итоговом html-документе не было проблем со списком литературы (внимательно смотрите, чтобы те слова, которые пишутся с большой буквы, писались с большой буквы, а то, что надо пивсать курсивом, было наисано курсивом)

2. Найти и скачать .csl файлы, соответсвующие трем вариантам стилей цитирования: ссылки номерами в алфавитном порядке, ссылки номерами в порядке упоминания, автор-год.

3. Прислать мне итоговый .bib и три .csl файла.


# **Часть 4.** Превращаем RMD в DOC
В этой части курса мы научимся преращать наш RMD в документ Word. Для этого будем спользовать RMD-шник Маси  и ее дополнительные материалы (она первая прислала ДЗ, поэтому ей и тапочки).

- [RMD файл, со вставленными ссылками](My_html_project/Masia.Rmd)
- [файл .bib с библиографическими данными](My_html_project/bibliography.bib)
- [modern-language-association-7th-edition-with-url.csl](My_html_project/modern-language-association-7th-edition-with-url.csl)
- [reproduction-fertility-and-development.csl](My_html_project/reproduction-fertility-and-development.csl)
- [scientia-agriculturae-bohemica.csl](My_html_project/scientia-agriculturae-bohemica.csl)
- [american-journal-of-botany.csl](My_html_project/american-journal-of-botany.csl)
- [hydrobiologia.csl](My_html_project/hydrobiologia.csl)
- [derjugin_style.csl](My_html_project/derjugin_style.csl)
- [marine-biology.csl](My_html_project/marine-biology.csl)
- [american-journal-of-botany.csl](My_html_project/american-journal-of-botany.csl)
- [brewingscience.csl](My_html_project/brewingscience.csl)
- [geosystem-engineering.csl](My_html_project/geosystem-engineering.csl)









