---
title: Курсы ЛЭМБ
description: Аннотации и объявления 
---
 
## контакты

- Хайтов Вадим Михайлович - polydora[]rambler.ru

## Содержание сайта
В настоящий момент на сайте выложены материалы по следующим курсам

**Advanced R (Вт, 17.00-19.00, 101 каб)**

То чем мы будем заниматься, можно назвать "литературным программированием". Основное внимание будет уделено знакомству с языком RMarkdown. С его помощью мы научимся создавать презентации, документы Word и даже интернет-сайты. Особое место в курсе будет уделено работе с библиографией и методам ее обработки и презентации в документах, создаваемых с помощью RMarkdown. Предполагается, что слушатели курса уже знакомы с языком R. На занятиях необходим ноутбук.

**Data Science (Ср, 17.00-19.00, 101 каб.)**
Мы рассмотрим методы обработки и визуализации данных, получаемых в научных исследованиях. Центральное место в курсе занимает знакомство с языком R, являющимся одним наиболее мощных инструментов обработки и визуализации данных. На занятиях необходим ноутбук